image: fedora:rawhide

variables:
  DEPENDENCIES:
    libtool
    gtk-doc
    autoconf
    automake
    gettext-devel
    gcc
    redhat-rpm-config
    gcc-c++
    glibc-devel
    make
    systemd
    sqlite-devel
    gobject-introspection-devel
    libusbx-devel
    libgudev-devel
    libimobiledevice-devel
    glib2-devel
    libplist-devel
    umockdev
    python3-dbus
    python3-dbusmock
  LAST_ABI_BREAK: "e294444496e8bbcd91a3605874f59562e14c34ec"

build_stable:
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - mkdir _build
    - cd _build
    - ../autogen.sh --with-idevice
    - make
    - make install
    - make check
    - make distcheck
  artifacts:
    when: on_success
    name: "upower-${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/upower-*.tar.xz"

check_abi:
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - curl https://gitlab.freedesktop.org/hadess/check-abi/-/raw/main/contrib/check-abi-fedora.sh | bash
    - check-abi --suppr .ci/upower.suppr ${LAST_ABI_BREAK} $(git rev-parse HEAD)
